packages/auth/package.json
packages/auth/utils/auth.ts

Update the version to the latest used in better-auth

refactor: 💡 Change the better-auth version

---

apps/backend-worker/src/index.ts
packages/api/src/index.ts
packages/auth/utils/auth.ts
packages/database/.env.local.example
packages/database/prisma/migrations/20250415234309_init/migration.sql
packages/database/prisma/schema/schema.prisma

Create a user in the database with betterAuth with email and password is working

feat: 🎸 /sign-up/email working

---

packages/api/src/index.ts

Delete unnecesary code and delete an unused route

fix: 🐛 Delete unnecesary code

---

packages/ui/global.css
packages/ui/src/components/button.tsx

A default style for the whole page

style: 💄 Button default

---

apps/web/src/modules/landing/slider-gallery.tsx
packages/ui/src/components/magicui/marquee.tsx

Correction of spacing of the first slider was made

STYLE: Slider component spacing correction

---

apps/web/src/modules/landing/hero.tsx
apps/web/src/modules/register/login-form.tsx
apps/web/src/utils/api-connection.ts
apps/web/tsconfig.json
bun.lock
package.json
packages/api/src/index.ts
packages/auth/client/index.ts
packages/auth/utils/auth.ts

- Added Google sign-in functionality in the LoginForm component.
- Created a new api-connection utility for handling authentication requests.
- Updated HeroSection to utilize session data from the auth client.
- Enhanced TypeScript configuration to include the new auth package path.
- Updated bun.lock and package.json to include new dependencies: axios and @tanstack/react-query.
- Adjusted auth client configuration to trust frontend and backend URLs.

🎸  feat: Integrate authentication and API connection

---

apps/web/src/modules/landing/about-landing.tsx
packages/ui/global.css

Styles were corrected in the “Abou-us” component and additionally, colors were corrected in the global.css.

STYLE: Correction of styles in the “About-us” component.

---

apps/web/src/modules/dashboard/paquetes/responsive-create-paquete.tsx

Corrected the spacing of the dashboard button component, and adjusted the width of the same component within the responsive view, so that it occupies the full width of the screen.

STYLE: Addition of spacing and correction in responsive view

---

apps/web/src/modules/auth/register-form.tsx
apps/web/src/modules/dashboard/paquetes/table-paquetes.tsx
apps/web/src/modules/dashboard/sidebar/dashboard-sidebar.tsx

Minimal changes were made in the organization of a component and additional folders were added corresponding to the functionalities of each item of the dashboard sidebar.

CHORE: Minimal changes of the organization of a component

---

apps/web/src/app/(private)/dashboard/paquetes/page.tsx
apps/web/src/app/(private)/dashboard/ventas/page.tsx
apps/web/src/app/(public)/layout.tsx
apps/web/src/modules/dashboard/paquetes/table-paquetes.tsx
apps/web/src/modules/dashboard/ventas/search-bar.tsx
apps/web/src/modules/dashboard/ventas/table-ventas.tsx

A “Search Bar” component has been added so that the information can be searched and reflected in the table.

FEAT: Addition of the search bar in the “Sales” section

---

apps/web/src/modules/dashboard/cupones/create-cupon-form.tsx
apps/web/src/modules/dashboard/cupones/table-cupones.tsx

A few text additions were made to make the tables more coherent.

STYLE: Adding text to tables

---

apps/web/src/modules/dashboard/paquetes/responsive-create-paquete.tsx
packages/api/src/modules/packages/packages.service.ts
packages/ui/src/components/badge.tsx

The `.env.local` file was modified in order to store the information of the package creation form.

FIX: Solution for saving photographic packages

---

apps/web/src/modules/dashboard/paquetes/responsive-update-paquete.tsx
apps/web/src/modules/dashboard/paquetes/update-paquete-form.tsx

Change the logic for the update package

fix: 🐛 Types fix

---

apps/web/src/modules/dashboard/paquetes/create-paquete-form.tsx
apps/web/src/modules/dashboard/paquetes/paquete-card.tsx
apps/web/src/modules/dashboard/paquetes/responsive-update-paquete.tsx
apps/web/src/modules/dashboard/paquetes/update-paquete-form.tsx
apps/web/src/services/package-service.ts
packages/api/src/modules/coupon/coupon.route.ts
packages/api/src/modules/coupon/coupon.service.ts
packages/api/src/modules/packages/packages.route.ts
packages/api/src/modules/packages/packages.service.ts
packages/api/src/modules/photographers/photographers.service.ts
packages/database/prisma/schema/migrations/20250429185810_db_update/migration.sql
packages/database/prisma/schema/other.prisma
packages/database/prisma/schema/schema.prisma

Change the db, use different syntax and change the names of the tables

fix: 🐛 Refactor the database

---

apps/web/src/modules/dashboard/cupones/responsive-update-cupon.tsx

Neft should fix this error that matches the database.

docs: ✏️ error in the code

---

apps/web/src/modules/dashboard/cupones/responsive-update-cupon.tsx
apps/web/src/modules/dashboard/cupones/update-cupon-form.tsx

Add the interface for type error

fix: 🐛 Create the fix for Remi

---

apps/web/src/modules/dashboard/paquetes/create-paquete-form.tsx
packages/ui/src/components/input.tsx

Formatting correction was made in the drawer, so that only the numerical value typed by the user is displayed

style: 💄 Correction of the format of the inputs in the drawer

---

apps/web/src/modules/dashboard/sidebar/dashboard-sidebar.tsx
apps/web/src/modules/dashboard/users/table-users.tsx

The table where all users will be located and roles can be managed has been created.

feat: 🎸 General table of users

---

apps/web/src/app/(private)/dashboard/admin/page.tsx
apps/web/src/app/(private)/dashboard/admin/usuarios/page.tsx
apps/web/src/app/(private)/dashboard/perfil/page.tsx
apps/web/src/hooks/use-users.tsx
apps/web/src/modules/dashboard/sidebar/dashboard-navbar.tsx
apps/web/src/modules/dashboard/sidebar/dashboard-sidebar.tsx
apps/web/src/modules/dashboard/users/table-users.tsx
apps/web/src/services/users-service.ts
apps/web/src/utils/get-roles-config.ts
packages/api/src/modules/users/users.route.ts
packages/api/src/modules/users/users.service.ts
packages/api/src/utils/betteAuthPlugin.ts
packages/auth/permissons/permissons.ts
packages/auth/utils/auth.ts
packages/ui/src/components/button.tsx

Add the users and table, endpoints still need to be developed

feat: 🎸 User table working

---

apps/web/src/modules/dashboard/horarios/aviability-manager.tsx
apps/web/src/modules/dashboard/horarios/store/use-date-store.ts
bun.lock
package.json
packages/api/src/modules/sessions/sessions.service.ts
packages/database/prisma/schema/migrations/20250507175612_fileds_for_clarity/migration.sql
packages/database/prisma/schema/other.prisma

feat: 🎸 Availability calendar update

---

apps/web/src/app/(private)/dashboard/metricas/page.tsx
apps/web/src/modules/dashboard/metricas/general-package-chart.tsx
apps/web/src/modules/dashboard/metricas/money-graph-chart.tsx
apps/web/src/modules/dashboard/metricas/package-graph-chart.tsx
apps/web/src/modules/dashboard/metricas/schedule-chart.tsx
apps/web/src/modules/dashboard/metricas/tab-metrics.tsx

We created graphs to have the general and specific metrics of packages sold, money earned, hours with more affluence and general qualification.

feat: 🎸 Addition of general and specific metrics

---

apps/web/src/app/(private)/dashboard/horarios/[id]/page.tsx
apps/web/src/app/(private)/dashboard/metricas/page.tsx
apps/web/src/modules/dashboard/metricas/general-package-chart.tsx
apps/web/src/modules/dashboard/metricas/money-graph-chart.tsx
apps/web/src/modules/dashboard/metricas/package-graph-chart.tsx
apps/web/src/modules/dashboard/metricas/schedule-chart.tsx
apps/web/src/modules/dashboard/metricas/tab-metrics.tsx

Use only grid where it's necesary and change the layout and color from the charts

:bug: (Metrics) Fix the layout in metrics

---

apps/web/src/app/(private)/dashboard/admin/metricas/page.tsx
apps/web/src/modules/dashboard/admin/metricas/money-general-chart.tsx
apps/web/src/modules/dashboard/admin/metricas/schedule-chart.tsx
apps/web/src/modules/dashboard/admin/metricas/topRated-photographer-chart.tsx
apps/web/src/modules/dashboard/admin/metricas/topSelling-photographer-chart.tsx
apps/web/src/modules/dashboard/admin/metricas/total-customers-chart.tsx
apps/web/src/modules/dashboard/admin/metricas/total-users-page.tsx
apps/web/src/modules/dashboard/ventas/table-ventas.tsx

Charts were made for the different roles within the application. General and specific graphs were made for the different roles.

feat: 🎸 Creation of graphs for statistical calculations

---

apps/web/src/modules/global/footer.tsx
apps/web/src/modules/landing/faq.tsx

Added the information corresponding to the FAQ and Footer.

style: 💄 Adding information to the footer and FAQ section

---

apps/web/src/app/(public)/agenda/page.tsx
apps/web/src/hooks/use-photographers.tsx
apps/web/src/modules/agenda/select-day.tsx
apps/web/src/modules/agenda/select-package.tsx
apps/web/src/modules/agenda/store/sale.store.ts
apps/web/src/services/photographer-service.ts
packages/api/src/modules/photographers/photographers.route.ts
packages/api/src/modules/photographers/photographers.service.ts

create the form to add the selection of the new horary and the creation of the endpoint in the server

:sparkles: (Horary) Day and horary added to the selection

---

apps/web/src/app/(private)/dashboard/horarios/[id]/page.tsx
apps/web/src/hooks/use-time-slots.tsx
apps/web/src/modules/auth/auth-screen.tsx
apps/web/src/modules/auth/login-form.tsx
apps/web/src/modules/auth/register-form.tsx
apps/web/src/modules/dashboard/cuenta/aditional-information-form.tsx
apps/web/src/modules/dashboard/horarios/time-slot-card.tsx
apps/web/src/modules/dashboard/paquetes/create-paquete-form.tsx
apps/web/src/services/profile-service.ts
apps/web/src/utils/auth-connection.ts
packages/auth/utils/auth.ts
packages/database/prisma/schema/migrations/20250522151217_phone_number_inside_the_app/migration.sql
packages/database/prisma/schema/other.prisma
packages/database/prisma/schema/schema.prisma
packages/ui/src/components/breadcrumb.tsx

Change in the landing page and also in the DB

:bug: (UI/UX) Fix many bugs and UX

---

apps/web/src/app/(public)/agenda/page.tsx
apps/web/src/modules/agenda/config/stepper.config.ts
apps/web/src/modules/agenda/confirm-payment.tsx
apps/web/src/modules/agenda/select-day.tsx
apps/web/src/modules/agenda/select-package.tsx
apps/web/src/modules/agenda/select-payment-method.tsx
apps/web/src/modules/agenda/select-photographer.tsx
apps/web/src/modules/agenda/store/sale.store.ts
packages/api/src/modules/coupon/coupon.service.ts

:sparkles: (Cart) Cart with all inputs fixed

---

apps/web/src/modules/dashboard/sidebar/dashboard-sidebar.tsx
apps/web/src/modules/dashboard/sidebar/nav-projects.tsx

Through conditions, a conditional sidebar was made according to the role of each user registered on the page.

feat: 🎸 Realization of a conditional Sidebar according to the r

---

apps/web/src/modules/global/footer.tsx
apps/web/src/modules/global/home-screen.tsx
apps/web/src/modules/landing/brand-card.tsx
apps/web/src/modules/landing/brands-carousel.tsx

A carrousel was made in the landing page, where the brands that collaborate with the project will go, in addition to this, an arrangement was made to the footer so that it can be seen well in all the responsive views.

feat: 🎸 Addition of the “Brands” section in the landing page

---

apps/web/package.json
apps/web/src/app/(private)/dashboard/perfil/page.tsx
apps/web/src/modules/dashboard/sidebar/dashboard-sidebar.tsx
bun.lock
packages/ui/src/icons/facebook-icon.tsx

React Icons library was installed to better accommodate the size and spacing of the icons

style: 💄 Correction of icons in profile section

---

apps/web/src/hooks/use-sale.tsx
apps/web/src/modules/dashboard/ventas/sheet-sale-details.tsx
apps/web/src/modules/dashboard/ventas/table-ventas.tsx
apps/web/src/services/sale-service.ts
packages/api/src/modules/sales/sale.route.ts
packages/api/src/modules/sales/sale.service.ts

Create the endpoints and the hook to cal the information in the frontend

:sparkles: (Sales) Photographer can see their sales

---

apps/web/src/app/layout.tsx
apps/web/src/modules/global/home-screen.tsx
apps/web/src/modules/global/navbar.tsx
apps/web/src/modules/landing/hero.tsx
apps/web/src/modules/landing/line.tsx
bun.lock
package.json
packages/ui/global.css

:art: (Change the landing page) Change the landing page to use Framer

---

apps/web/src/modules/dashboard/metricas/customer-graph-chart.tsx
apps/web/src/modules/dashboard/metricas/money-graph-chart.tsx
apps/web/src/modules/dashboard/metricas/package-graph-chart.tsx
apps/web/src/modules/dashboard/sidebar/dashboard-sidebar.tsx
apps/web/src/modules/dashboard/sidebar/nav-projects.tsx
bun.lock
package.json
packages/ui/global.css

Create a new schema color, less contrast and create a beatuyfull background gradient

:art: (Global CSS) Change the schema color

---

apps/web/src/app/(private)/(staff)/photographer/ventas/page.tsx
apps/web/src/modules/dashboard/cupones/cupones-table.tsx
apps/web/src/modules/dashboard/paquetes/paquete-card.tsx
apps/web/src/modules/dashboard/sidebar/nav-user.tsx
apps/web/src/modules/dashboard/ventas/sheet-sale-details.tsx
apps/web/src/modules/dashboard/ventas/table-ventas.tsx
apps/web/src/modules/dashboard/ventas/ventas-filters.tsx
apps/web/src/modules/dashboard/ventas/ventas-header.tsx
apps/web/src/modules/dashboard/ventas/ventas-table.tsx

Change the UI from the table of sales

:art: (Table) Table Sales

---

apps/web/src/modules/agenda/user-data.tsx
apps/web/src/modules/dashboard/ventas/ventas-detalles.tsx
apps/web/src/modules/dashboard/ventas/ventas-table.tsx
apps/web/src/modules/global/navbar.tsx
packages/api/src/modules/sales/sale.service.ts

Create the last steps for agenda a session

:sparkles: (OTP) Function as OTP

---

apps/web/src/modules/landing/hero.tsx
apps/web/src/modules/landing/modal-ticket.tsx
apps/web/src/modules/landing/team.tsx

Esta PR introduce mejoras significativas en la experiencia de usuario del landing page, agregando funcionalidad para consulta de tickets y mejorando el diseño de la sección de equipo.
🚀 Cambios Principales:
✨ Nueva Funcionalidad:
•  🎟️ ModalTicket Component: Nuevo componente modal integrado al HeroSection para consulta de tickets
◦  Funcionalidad simulada de consulta de tickets
◦  Integración seamless con la sección hero
🎨 Mejoras de Diseño:
•  👥 TeamSection: Actualización del layout y diseño de cards
◦  Mejor responsividad en diferentes dispositivos
◦  Mejora visual del diseño de las tarjetas del equipo
◦  Layout más atractivo y moderno
🧪 Cómo Probar:
ModalTicket:
Verificar que el botón/trigger del modal aparece correctamente en HeroSection
Confirmar que el modal se abre y cierra …

feat: Add ticket consultation modal and improve team section design 
